- name: Create service user
  block:
    - name: Create monitor group
      ansible.builtin.group:
        name: "{{ app_name }}"
        state: present

    - name: Create monitor user
      ansible.builtin.user:
        name: "{{ app_name }}"
        comment: "Service account for running {{ app_name }}"
        shell: /usr/sbin/nologin
        home: "{{ app_home }}"
        create_home: true
        system: true
