- name: Create service user
  block:
    - name: Create monitor group
      ansible.builtin.group:
        name: "{{ app_name }}"
        state: present

    - name: Create monitor user
      ansible.builtin.user:
        name: "{{ app_name }}"
        comment: "Service account for running {{ app_name }}"
        shell: /usr/sbin/nologin
        create_home: false
        system: true

- name: Create monitor home directory
  ansible.builtin.file:
    path: "{{ app_home }}"
    state: directory
    owner: "{{ app_name }}"
    group: "{{ app_name }}"
    mode: "0700"
